## The Weather Dataset

In [ ]:
Here The Weather Dataset is a Time-Series Dataset With Per-Hour Information About The Weather Conditions at a
Particular Location it records Temperature, Dew Point Temperature, Relative Humidity, Wind Speed Visibility, Pressure
and Condition.

## Importing Library

In [1]:
import pandas as pd
import numpy as np

In [15]:
data = pd.read_csv("C:\\Users\\dell\\Desktop\\1. Weather Data.csv")

In [5]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [16]:
data.shape

(8784, 8)

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [18]:
data["Date/Time"] = pd.to_datetime(data["Date/Time"])

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   datetime64[ns]
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB

In [12]:
data["Weather"].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

### Q) 1. Find all the unique wind speed values in the data

In [21]:
data["Wind Speed_km/h"].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

### Q 2) Find the number of times when the weather is exactly clear.

In [30]:
data[data["Weather"]== "Clear"]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,2012-01-05 18:00:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,2012-01-05 19:00:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,2012-01-05 20:00:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,2012-01-05 21:00:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,2012-12-26 06:00:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,2012-12-28 10:00:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,2012-12-29 01:00:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,2012-12-29 02:00:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear

### Q 3) Find the number of times when the wind speed was exactly 4km/h

In [31]:
data[data["Wind Speed_km/h"] == 4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,2012-01-05 00:00:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,2012-01-05 05:00:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,2012-01-07 02:00:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,2012-12-31 08:00:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,2012-12-31 09:00:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,2012-12-31 10:00:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,2012-12-31 12:00:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,2012-12-31 13:00:00,-4.6,-6.6,86,4,12.9,100.63,Snow

### Q 4) Find out the all null values in the data.

In [32]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

### Q 5) Rename the column name weather of the dataframe to weather condition

In [38]:
data.rename(columns = {"Weather" : "Weather condition"},inplace = True)

### Q 6) What is the mean visibility

In [40]:
data["Visibility_km"].mean()

27.664446721311478

### Q 7) What is the standard deviation of pressure in this data

In [41]:
data["Press_kPa"].std()

0.8440047459486474

### Q 8) What is the Variance of Relative Humidity in this data

In [42]:
data["Rel Hum_%"].var()

286.2485501984998

### Q 9) Find all instances when snow was recorded.

In [44]:
data[data["Weather condition"].str.contains("Snow")]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

### Q 10) Find all instances when wind speed is above 24 and visibility is 25

In [46]:
data[(data["Wind Speed_km/h"] > 24) & (data["Visibility_km"] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,2012-01-02 02:00:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,2012-01-02 03:00:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,2012-12-28 17:00:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,2012-12-30 17:00:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,2012-12-30 19:00:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,2012-12-30 23:00:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,2012-12-31 00:00:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

### Q 11) What is the mean value of each column against each weather condition

In [47]:
data.groupby("Weather condition").mean()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather condition,,,,,,,
Clear,2012-06-25 18:03:12.760180992,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,2012-07-01 16:51:29.583333376,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,2012-09-17 15:00:00.000000000,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",2012-06-30 00:44:15.000000000,8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",2012-12-17 09:00:00.000000000,0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000
"Drizzle,Snow",2012-12-18 16:30:00.000000000,1.050000,0.150000,93.500000,14.000000,10.500000,100.890000
"Drizzle,Snow,Fog",2012-12-19 20:56:00.000000000,0.693333,0.120000,95.866667,15.533333,5.513333,99.281333
Fog,2012-06-24 21:08:00.000000000,4.303333,3.159333,92.286667,7.946667,6.248000,101.184067
Freezing Drizzle,2012-03-05 23:25:42.857142784,-5.657143,-8.000000,83.571429,16.571429,9.200000,100.202857
"Freezing Drizzle,Fog",2012-04-30 06:20:00.000000000,-2.533333,-4.183333,88.500000,17.000000,5.266667,100.441667
"Freezing Drizzle,Haze",2012-02-01 12:00:00.000000000,-5.433333,-8.000000,82.000000,10.333333,2.666667,100.316667
"Freezing Drizzle,Snow",2012-06-27 12:32:43.636363520,-5.109091,-7.072727,86.090909,16.272727,5.872727,100.520909
Freezing Fog,2012-02-22 06:45:00.000000000,-7.575000,-9.250000,87.750000,4.750000,0.650000,102.320000
Freezing Rain,2012-02-14 01:34:17.142857216,-3.885714,-6.078571,84.642857,19.214286,8.242857,99.647143
"Freezing Rain,Fog",2012-06-28 15:45:00.000000000,-2.225000,-3.750000,89.500000,15.500000,7.550000,99.945000
"Freezing Rain,Haze",2012-02-01 14:30:00.000000000,-4.900000,-7.450000,82.500000,7.500000,2.400000,100.375000
"Freezing Rain,Ice Pellets,Fog",2012-12-17 03:00:00.000000000,-2.600000,-3.700000,92.000000,28.000000,8.000000,100.950000
"Freezing Rain,Snow Grains",2012-01-13 09:00:00.000000000,-5.000000,-7.300000,84.000000,32.000000,4.800000,98.560000
Haze,2012-06-06 00:37:30.000000000,-0.200000,-2.975000,81.625000,10.437500,7.831250,101.482500
Mainly Clear,2012-07-12 06:48:08.888888832,12.558927,4.581671,60.667142,14.144824,34.264862,101.248832
"Moderate Rain,Fog",2012-12-10 08:00:00.000000000,1.700000,0.800000,94.000000,17.000000,6.400000,99.980000
Moderate Snow,2012-07-05 12:00:00.000000000,-5.525000,-7.250000,87.750000,33.750000,0.750000,100.275000
"Moderate Snow,Blowing Snow",2012-12-27 11:00:00.000000000,-5.450000,-6.500000,92.500000,40.000000,0.600000,100.570000
Mostly Cloudy,2012-07-01 10:42:53.417109760,10.574287,3.131174,62.102465,15.813920,31.253842,101.025288
Rain,2012-07-02 07:18:02.352941056,9.786275,7.042810,83.624183,19.254902,18.856536,100.233333
Rain Showers,2012-07-14 17:25:51.063829760,13.722340,9.187766,75.159574,17.132979,22.816489,100.404043
"Rain Showers,Fog",2012-10-20 03:00:00.000000000,12.800000,12.100000,96.000000,13.000000,6.400000,99.830000
"Rain Showers,Snow Showers",2012-11-19 21:00:00.000000000,2.150000,-1.500000,76.500000,22.500000,21.700000,101.100000
"Rain,Fog",2012-08-17 05:19:08.275862016,8.273276,7.219828,93.189655,14.793103,6.873276,100.500862
"Rain,Haze",2012-03-13 08:00:00.000000000,4.633333,2.066667,83.333333,11.666667,6.700000,100.540000
"Rain,Ice Pellets",2012-12-18 05:00:00.000000000,0.600000,-0.600000,92.000000,24.000000,9.700000,100.120000
"Rain,Snow",2012-07-22 00:23:20.000000000,1.055556,-0.566667,89.000000,28.388889,11.672222,99.951111
"Rain,Snow Grains",2012-12-21 00:00:00.000000000,1.900000,-2.100000,75.000000,26.000000,25.000000,100.600000
"Rain,Snow,Fog",2012-12-08 21:00:00.000000000,0.800000,0.300000,96.000000,9.000000,6.400000,100.730000
"Rain,Snow,Ice Pellets",2012-12-21 03:15:00.000000000,1.100000,-0.175000,91.500000,23.250000,6.000000,100.105000
Snow,2012-04-18 19:10:36.923076864,-4.524103,-7.623333,79.307692,20.038462,11.171795,100.536103
Snow Pellets,2012-11-24 15:00:00.000000000,0.700000,-6.400000,59.000000,35.000000,2.400000,99.700000
Snow Showers,2012-07-21 22:40:59.999999744,-3.506667,-7.866667,72.350000,19.233333,20.158333,100.963500
"Snow Showers,Fog",2012-12-28 17:15:00.000000000,-10.675000,-11.900000,90.750000,13.750000,7.025000,101.292500
"Snow,Blowing Snow",2012-08-08 17:44:12.631578880,-5.410526,-7.621053,84.473684,34.842105,4.105263,99.704737
"Snow,Fog",2012-10-21 17:42:09.729729792,-5.075676,-6.364865,90.675676,17.324324,4.537838,100.688649
"Snow,Haze",2012-02-01 19:00:00.000000000,-4.020000,-6.860000,80.600000,5.000000,4.640000,100.782000
"Snow,Ice Pellets",2012-09-14 21:00:00.000000000,-1.883333,-3.666667,87.666667,23.833333,7.416667,100.548333
Thunderstorms,2012-07-10 08:30:00.000000000,24.150000,19.750000,77.000000,7.500000,24.550000,100.230000
"Thunderstorms,Heavy Rain Showers",2012-05-29 06:00:00.000000000,10.900000,9.000000,88.000000,9.000000,2.400000,100.260000
"Thunderstorms,Moderate Rain Showers,Fog",2012-07-17 06:00:00.000000000,19.600000,18.500000,93.000000,15.000000,3.200000,100.010000
"Thunderstorms,Rain",2012-07-04 02:20:00.000000000,20.433333,18.533333,89.000000,15.666667,19.833333,100.420000
"Thunderstorms,Rain Showers",2012-07-18 14:48:45.000000000,20.037500,17.618750,86.375000,18.312500,15.893750,100.233750
"Thunderstorms,Rain Showers,Fog",2012-07-16 02:40:00.000000000,21.600000,18.700000,84.000000,19.666667,9.700000,100.063333
"Thunderstorms,Rain,Fog",2012-07-17 05:00:00.000000000,20.600000,18.600000,88.000000,19.000000,4.800000,100.080000

### Q 12) What is the maximum and minimum value of each column against each weather condition

In [53]:
data.groupby("Weather condition").agg(["min","max"])

                                                  Date/Time  \
                                                        min
Weather condition
Clear                                   2012-01-03 19:00:00
Cloudy                                  2012-01-01 17:00:00
Drizzle                                 2012-01-23 21:00:00
Drizzle,Fog                             2012-01-23 20:00:00
Drizzle,Ice Pellets,Fog                 2012-12-17 09:00:00
Drizzle,Snow                            2012-12-17 15:00:00
Drizzle,Snow,Fog                        2012-12-18 21:00:00
Fog                                     2012-01-01 00:00:00
Freezing Drizzle                        2012-01-07 11:00:00
Freezing Drizzle,Fog                    2012-01-01 02:00:00
Freezing Drizzle,Haze                   2012-02-01 11:00:00
Freezing Drizzle,Snow                   2012-01-13 03:00:00
Freezing Fog                            2012-01-22 06:00:00
Freezing Rain                           2012-01-07 10:00:00
Freezing Rain,Fog                       2012-01-07 09:00:00
Freezing Rain,Haze                      2012-02-01 14:00:00
Freezing Rain,Ice Pellets,Fog           2012-12-17 03:00:00
Freezing Rain,Snow Grains               2012-01-13 09:00:00
Haze                                    2012-01-22 12:00:00
Mainly Clear                            2012-01-02 12:00:00
Moderate Rain,Fog                       2012-12-10 08:00:00
Moderate Snow                           2012-01-12 15:00:00
Moderate Snow,Blowing Snow              2012-12-27 10:00:00
Mostly Cloudy                           2012-01-01 16:00:00
Rain                                    2012-01-01 18:00:00
Rain Showers                            2012-01-01 22:00:00
Rain Showers,Fog                        2012-10-20 03:00:00
Rain Showers,Snow Showers               2012-11-04 08:00:00
Rain,Fog                                2012-01-23 18:00:00
Rain,Haze                               2012-03-13 07:00:00
Rain,Ice Pellets                        2012-12-18 05:00:00
Rain,Snow                               2012-01-10 05:00:00
Rain,Snow Grains                        2012-12-21 00:00:00
Rain,Snow,Fog                           2012-12-08 21:00:00
Rain,Snow,Ice Pellets                   2012-12-21 01:00:00
Snow                                    2012-01-03 07:00:00
Snow Pellets                            2012-11-24 15:00:00
Snow Showers                            2012-01-02 17:00:00
Snow Showers,Fog                        2012-12-26 09:00:00
Snow,Blowing Snow                       2012-01-13 21:00:00
Snow,Fog                                2012-02-10 23:00:00
Snow,Haze                               2012-02-01 17:00:00
Snow,Ice Pellets                        2012-03-03 04:00:00
Thunderstorms                           2012-07-04 16:00:00
Thunderstorms,Heavy Rain Showers        2012-05-29 06:00:00
Thunderstorms,Moderate Rain Showers,Fog 2012-07-17 06:00:00
Thunderstorms,Rain                      2012-05-25 20:00:00
Thunderstorms,Rain Showers              2012-05-29 04:00:00
Thunderstorms,Rain Showers,Fog          2012-06-29 03:00:00
Thunderstorms,Rain,Fog                  2012-07-17 05:00:00

                                                            Temp_C        \
                                                        max    min   max
Weather condition
Clear                                   2012-12-30 20:00:00  -23.3  32.8
Cloudy                                  2012-12-31 06:00:00  -21.4  30.5
Drizzle                                 2012-12-22 01:00:00    1.1  18.8
Drizzle,Fog                             2012-12-19 10:00:00    0.0  19.9
Drizzle,Ice Pellets,Fog                 2012-12-17 09:00:00    0.4   0.4
Drizzle,Snow                            2012-12-19 18:00:00    0.9   1.2
Drizzle,Snow,Fog                        2012-12-22 03:00:00    0.3   1.1
Fog                                     2012-12-29 10:00:00  -16.0  20.8
Freezing Drizzle                        2012-12-17 00:00:00   -9.0  -2.3
Freezing Drizzle,Fog                    2012-12-10 05:00:00   -6.4  -0.3
Freezing Drizzle,Haze                   2012-02-01 13:00:00   -5.8  -5.0
Freezing Drizzle,Snow                   2012-12-28 02:00:00   -8.3  -3.3
Freezing Fog                            2012-03-17 06:00:00  -19.0  -0.1
Freezing Rain                           2012-12-17 02:00:00   -6.5   0.3
Freezing Rain,Fog                       2012-12-17 01:00:00   -6.1   0.1
Freezing Rain,Haze                      2012-02-01 15:00:00   -4.9  -4.9
Freezing Rain,Ice Pellets,Fog           2012-12-17 03:00:00   -2.6  -2.6
Freezing Rain,Snow Grains               2012-01-13 09:00:00   -5.0  -5.0
Haze                                    2012-12-13 12:00:00  -11.5  14.1
Mainly Clear                            2012-12-30 22:00:00  -22.8  33.0
Moderate Rain,Fog                       2012-12-10 08:00:00    1.7   1.7
Moderate Snow                           2012-12-27 09:00:00   -6.3  -4.9
Moderate Snow,Blowing Snow              2012-12-27 12:00:00   -5.5  -5.4
Mostly Cloudy                           2012-12-31 03:00:00  -23.2  32.4
Rain                                    2012-12-21 21:00:00    0.3  22.8
Rain Showers                            2012-12-14 11:00:00    1.6  26.4
Rain Showers,Fog                        2012-10-20 03:00:00   12.8  12.8
Rain Showers,Snow Showers               2012-12-05 10:00:00    2.1   2.2
Rain,Fog                                2012-12-10 17:00:00    0.0  21.7
Rain,Haze                               2012-03-13 09:00:00    4.0   5.5
Rain,Ice Pellets                        2012-12-18 05:00:00    0.6   0.6
Rain,Snow                               2012-12-21 09:00:00    0.6   1.7
Rain,Snow Grains                        2012-12-21 00:00:00    1.9   1.9
Rain,Snow,Fog                           2012-12-08 21:00:00    0.8   0.8
Rain,Snow,Ice Pellets                   2012-12-21 05:00:00    0.9   1.3
Snow                                    2012-12-31 23:00:00  -16.7   3.7
Snow Pellets                            2012-11-24 15:00:00    0.7   0.7
Snow Showers                            2012-12-31 08:00:00  -13.3   2.9
Snow Showers,Fog                        2012-12-29 13:00:00  -11.3 -10.0
Snow,Blowing Snow                       2012-12-27 19:00:00  -12.0  -1.4
Snow,Fog                                2012-12-31 10:00:00  -10.1   1.1
Snow,Haze                               2012-02-01 21:00:00   -4.3  -3.6
Snow,Ice Pellets                        2012-12-17 06:00:00   -4.3   0.8
Thunderstorms                           2012-07-16 01:00:00   21.6  26.7
Thunderstorms,Heavy Rain Showers        2012-05-29 06:00:00   10.9  10.9
Thunderstorms,Moderate Rain Showers,Fog 2012-07-17 06:00:00   19.6  19.6
Thunderstorms,Rain                      2012-07-23 18:00:00   19.4  21.3
Thunderstorms,Rain Showers              2012-09-14 20:00:00   11.0  25.5
Thunderstorms,Rain Showers,Fog          2012-07-31 20:00:00   19.5  22.9
Thunderstorms,Rain,Fog                  2012-07-17 05:00:00   20.6  20.6

                                        Dew Point Temp_C       Rel Hum_%       \
                                                     min   max       min  max
Weather condition
Clear                                              -28.5  20.4        20   99
Cloudy                                             -26.8  22.6        18   99
Drizzle                                             -0.2  17.7        74   96
Drizzle,Fog                                         -1.6  19.1        85  100
Drizzle,Ice Pellets,Fog                             -0.7  -0.7        92   92
Drizzle,Snow                                         0.1   0.2        92   95
Drizzle,Snow,Fog                                    -0.1   0.6        92   98
Fog                                                -17.2  19.6        80  100
Freezing Drizzle                                   -12.2  -3.3        78   93
Freezing Drizzle,Fog                                -9.0  -2.3        82   94
Freezing Drizzle,Haze                               -8.3  -7.7        81   83
Freezing Drizzle,Snow                              -10.4  -4.6        79   94
Freezing Fog                                       -22.9  -0.3        71   99
Freezing Rain                                       -9.0  -1.7        81   92
Freezing Rain,Fog                                   -8.7  -0.9        82   93
Freezing Rain,Haze                                  -7.5  -7.4        82   83
Freezing Rain,Ice Pellets,Fog                       -3.7  -3.7        92   92
Freezing Rain,Snow Grains                           -7.3  -7.3        84   84
Haze                                               -16.0  11.1        68   86
Mainly Clear                                       -28.0  21.2        20   99
Moderate Rain,Fog                                    0.8   0.8        94   94
Moderate Snow                                       -7.6  -6.7        83   93
Moderate Snow,Blowing Snow                          -6.6  -6.4        92   93
Mostly Cloudy                                      -28.5  24.4        18  100
Rain                                                -5.7  20.4        40   99
Rain Showers                                        -7.2  23.0        37   97
Rain Showers,Fog                                    12.1  12.1        96   96
Rain Showers,Snow Showers                           -1.8  -1.2        75   78
Rain,Fog                                            -1.2  19.5        83  100
Rain,Haze                                            1.0   2.9        81   86
Rain,Ice Pellets                                    -0.6  -0.6        92   92
Rain,Snow                                           -1.7   0.5        81   94
Rain,Snow Grains                                    -2.1  -2.1        75   75
Rain,Snow,Fog                                        0.3   0.3        96   96
Rain,Snow,Ice Pellets                               -0.7   0.1        88   94
Snow                                               -24.6   0.3        41   96
Snow Pellets                                        -6.4  -6.4        59   59
Snow Showers                                       -19.3  -0.7        52   94
Snow Showers,Fog                                   -12.7 -11.1        89   92
Snow,Blowing Snow                                  -16.2  -2.9        70   91
Snow,Fog                                           -12.0   0.8        77   99
Snow,Haze                                           -7.2  -6.4        80   81
Snow,Ice Pellets                                    -5.9  -1.7        76   92
Thunderstorms                                       19.4  20.1        67   87
Thunderstorms,Heavy Rain Showers                     9.0   9.0        88   88
Thunderstorms,Moderate Rain Showers,Fog             18.5  18.5        93   93
Thunderstorms,Rain                                  18.2  19.1        83   93
Thunderstorms,Rain Showers                           7.0  23.1        68   98
Thunderstorms,Rain Showers,Fog                      16.1  21.3        80   91
Thunderstorms,Rain,Fog                              18.6  18.6        88   88

                                        Wind Speed_km/h     Visibility_km  \
                                                    min max           min
Weather condition
Clear                                                 0  33          11.3
Cloudy                                                0  54          11.3
Drizzle                                               0  30           6.4
Drizzle,Fog                                           0  28           1.0
Drizzle,Ice Pellets,Fog                              20  20           4.0
Drizzle,Snow                                          9  19           9.7
Drizzle,Snow,Fog                                      7  32           2.4
Fog                                                   0  22           0.2
Freezing Drizzle                                      6  26           4.8
Freezing Drizzle,Fog                                  6  33           3.6
Freezing Drizzle,Haze                                 9  11           2.0
Freezing Drizzle,Snow                                 6  24           2.4
Freezing Fog                                          0   9           0.2
Freezing Rain                                         7  28           2.8
Freezing Rain,Fog                                     7  26           2.8
Freezing Rain,Haze                                    6   9           2.0
Freezing Rain,Ice Pellets,Fog                        28  28           8.0
Freezing Rain,Snow Grains                            32  32           4.8
Haze                                                  0  17           4.8
Mainly Clear                                          0  63          12.9
Moderate Rain,Fog                                    17  17           6.4
Moderate Snow                                        26  39           0.6
Moderate Snow,Blowing Snow                           39  41           0.6
Mostly Cloudy                                         0  83          11.3
Rain                                                  0  52           4.0
Rain Showers                                          0  41           6.4
Rain Showers,Fog                                     13  13           6.4
Rain Showers,Snow Showers                            17  28          19.3
Rain,Fog                                              0  46           2.0
Rain,Haze                                             7  17           4.0
Rain,Ice Pellets                                     24  24           9.7
Rain,Snow                                            13  52           2.4
Rain,Snow Grains                                     26  26          25.0
Rain,Snow,Fog                                         9   9           6.4
Rain,Snow,Ice Pellets                                17  28           4.8
Snow                                                  0  57           1.0
Snow Pellets                                         35  35           2.4
Snow Showers                                          0  37           2.4
Snow Showers,Fog                                      7  22           4.0
Snow,Blowing Snow                                    24  48           0.6
Snow,Fog                                              4  35           1.2
Snow,Haze                                             0  15           4.0
Snow,Ice Pellets                                     19  33           2.8
Thunderstorms                                         0  15          24.1
Thunderstorms,Heavy Rain Showers                      9   9           2.4
Thunderstorms,Moderate Rain Showers,Fog              15  15           3.2
Thunderstorms,Rain                                    4  30          16.1
Thunderstorms,Rain Showers                            7  32           6.4
Thunderstorms,Rain Showers,Fog                        7  35           9.7
Thunderstorms,Rain,Fog                               19  19           4.8

                                              Press_kPa
                                          max       min     max
Weather condition
Clear                                    48.3     99.52  103.63
Cloudy                                   48.3     98.39  103.65
Drizzle                                  25.0     97.84  101.56
Drizzle,Fog                               9.7     98.65  102.07
Drizzle,Ice Pellets,Fog                   4.0    100.79  100.79
Drizzle,Snow                             11.3    100.63  101.15
Drizzle,Snow,Fog                          9.7     97.79  100.15
Fog                                       9.7     98.31  103.04
Freezing Drizzle                         12.9     98.44  101.02
Freezing Drizzle,Fog                      8.0     98.74  101.27
Freezing Drizzle,Haze                     4.0    100.28  100.36
Freezing Drizzle,Snow                    12.9     99.19  101.18
Freezing Fog                              0.8    101.97  102.85
Freezing Rain                            16.1     98.22  101.00
Freezing Rain,Fog                         9.7     98.32  101.01
Freezing Rain,Haze                        2.8    100.34  100.41
Freezing Rain,Ice Pellets,Fog             8.0    100.95  100.95
Freezing Rain,Snow Grains                 4.8     98.56   98.56
Haze                                      9.7    100.35  102.97
Mainly Clear                             48.3     98.67  103.59
Moderate Rain,Fog                         6.4     99.98   99.98
Moderate Snow                             0.8     99.88  100.67
Moderate Snow,Blowing Snow                0.6    100.50  100.64
Mostly Cloudy                            48.3     98.36  103.65
Rain                                     48.3     97.52  102.26
Rain Showers                             48.3     98.51  102.31
Rain Showers,Fog                          6.4     99.83   99.83
Rain Showers,Snow Showers                24.1    101.09  101.11
Rain,Fog                                  9.7     98.61  101.77
Rain,Haze                                 9.7    100.50  100.61
Rain,Ice Pellets                          9.7    100.12  100.12
Rain,Snow                                25.0     98.18  101.07
Rain,Snow Grains                         25.0    100.60  100.60
Rain,Snow,Fog                             6.4    100.73  100.73
Rain,Snow,Ice Pellets                     6.4     99.85  100.47
Snow                                     25.0     97.75  102.73
Snow Pellets                              2.4     99.70   99.70
Snow Showers                             48.3     99.49  102.50
Snow Showers,Fog                          9.7    100.63  102.52
Snow,Blowing Snow                         9.7     98.11  100.62
Snow,Fog                                  9.7     99.38  102.07
Snow,Haze                                 6.4    100.61  100.99
Snow,Ice Pellets                         11.3     99.40  100.96
Thunderstorms                            25.0     99.84  100.62
Thunderstorms,Heavy Rain Showers          2.4    100.26  100.26
Thunderstorms,Moderate Rain Showers,Fog   3.2    100.01  100.01
Thunderstorms,Rain                       24.1    100.19  100.83
Thunderstorms,Rain Showers               25.0     99.65  101.06
Thunderstorms,Rain Showers,Fog            9.7     99.71  100.64
Thunderstorms,Rain,Fog                    4.8    100.08  100.08

### Q 13) Show all records where weather condition is Fog

In [56]:
data[data["Weather condition"] == "Fog"]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,2012-12-29 04:00:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,2012-12-29 05:00:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,2012-12-29 06:00:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,2012-12-29 07:00:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,2012-12-29 10:00:00,-12.0,-13.3,90,7,6.4,101.15,Fog

### Q 14) Find all instances when weather is clear or visibility is 40

In [57]:
data[(data["Weather condition"] == "Clear") | (data["Visibility_km"] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
106,2012-01-05 10:00:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,2012-01-05 11:00:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,2012-01-05 12:00:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,2012-01-05 13:00:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,2012-12-30 13:00:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,2012-12-30 14:00:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,2012-12-30 15:00:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,2012-12-30 16:00:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear

### Q 15) Find all instances when
###    A. Weather is clear and Relative Humidity is greater then 50
####    B. Visibility is above 40

In [59]:
data[(data["Weather condition"] == "Clear") & (data["Rel Hum_%"] >50)|(data["Visibility_km"] >40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
106,2012-01-05 10:00:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,2012-01-05 11:00:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,2012-01-05 12:00:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,2012-01-05 13:00:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,2012-01-05 14:00:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,2012-12-30 13:00:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,2012-12-30 14:00:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,2012-12-30 15:00:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,2012-12-30 16:00:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear